### ISSUE TITLE
Let's rewrite the UI Toolkit using the already made eGUI demo called Widget Gallery 

### ISSUE THREAD

**Issue by danieldia-dev** [Avdan-OS/qml-toolkit#18]
[](https://github.com/emilk/egui/blob/master/crates/egui_demo_lib/src/demo/widget_gallery.rs)
[](https://www.egui.rs/index.html#demo)

**Comment by danieldia-dev** [comment]
https://www.egui.rs/index.html#demo

https://github.com/emilk/egui/blob/master/crates/egui_demo_lib/src/demo/widget_gallery.rs

**Comment by ghost** [comment]
We don't need the widget gallery model, we can just simy the model what we're using. It's clean and good. Why we have to rewrite things everytiime?
