### ISSUE TITLE
Moving to iced

### ISSUE THREAD

**Issue by akaneboy** [Avdan-OS/qml-toolkit#25]
I don't really know why we chose to use egui, because egui is an immediate-mode gui library, which is pretty basic and we can't store any real complex data. Also egui is basically used for writing simple and small application, not OS apps! In opposition to egui, iced is retained-mode and with that we are able to build more complex apps.

**Comment by Froxcey** [comment]
Yes I agree. I mean, I don't know what else to say...

![vibe](https://user-images.githubusercontent.com/51555391/176177206-ec3f9dce-8780-4fe8-b6ac-5eeeac2038d4.gif)

**Comment by akaneboy** [comment]
@Sammy99jsp what do you think boss

**Comment by Sammy99jsp** [comment]
I tried out EGUI and I couldn't easily see a way to customize it easily.
